name: Daily Deploy

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: List directory contents
      run: ls -la
    
    - name: Display package.json
      run: cat package.json
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Install dependencies
      run: npm install
    
    - name: Generate blog post and build site
      run: npm run generate-and-build
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add daily blog post" || echo "No changes to commit"
        git push "https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}