name: Daily Deploy

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Set a 15-minute timeout for the entire job
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: List directory contents
      run: ls -la
    
    - name: Display package.json
      run: cat package.json
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Install Node.js dependencies
      run: npm install

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
    
    - name: Generate blog posts
      run: python generate_blog_post.py
      timeout-minutes: 5  # Set a 5-minute timeout for blog post generation
    
    - name: Build site
      run: npm run docs:build
      timeout-minutes: 5  # Set a 5-minute timeout for site building
    
    - name: Commit and push changes
      run: |
        git config --local user.name 'Tenx'
        git config --local user.email '86tenx@gmail.com'
        git add .
        git commit -m "Add daily blog post" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
