name: Daily Deploy

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate blog post and build site
      run: npm run generate-and-build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: Tenx/travelchina
        publish_branch: gh-pages
        publish_dir: ./docs/.vitepress/dist